### ISSUE TITLE
EPIC: DevShop 1.x: Upgrade to Aegir 3

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#30]
# Summary

We're moving to Aegir 3: Devmaster on Drupal 7. Hosting Drupal 8

It's in the 1.x branch of [this repo](https://github.com/opendevshop/devshop/tree/1.x) and [devmaster repo](https://github.com/opendevshop/devmaster/tree/1.x).

DevShop 1.x Pull Request: https://github.com/opendevshop/devshop/pull/44
DevMaster 1.x Pull Request: https://github.com/opendevshop/devmaster/pull/8

I think we should not actually merge these pull requests, but keep the 0.x branch around for posterity.

The Pull Requests are good for running tests and discussing the minutiae of the development work.
# Contributing

If you find a problem, and can edit this issue, please add it to the list.  If you can't, post it as a comment.

Please submit pull requests against the 1.x branch, (which is not the default.)

Thanks!
## Tests

We now have an extremely easy way to run tests against your devshop server:

``` sh
aegir@devshop:~$ devshop devmaster:test
```

Run this command as the aegir user to run our suite of Behat tests.

Be aware it will go through and attempt to create a project and environments on your server.  If it fails, you might have to go back in and destroy the project yourself before the test will pass again.

Let's take this opportunity to write more tests against these bugs.  I think it will help for the project leads to create some of the initial pull requests by writing a failing test.  Then, a developer can be assigned and they can work until the test passes.
- [ ] Improve Testing Documentation: We need to add a section to the devshop documentation explaining the testing infrastructure that we created.  
### MAJOR ISSUES

Do we have any more major issues? :dancer: 
### UI ISSUES
- [ ] Certain tasks should go to the task logs page. It's nice to show people deploys and test runs immediately.
- [ ] Install Site task doesn't save itself into environment "last_task", so it doesn't appear on environment dashboard.
- [ ] Upgrade from 0.x does not work yet...
- [ ] Confirm DevShop Testing fully works, for D7 and D8
- [ ] Confirm devshop_acquia module works.
- [ ] Confirm devshop_dothooks module works.
### Drupal 8 Issues:
- [ ] Block "registry rebuild" for drupal 8 sites.
- [ ] Sync data still runs registry rebuild and cache-clear, even if on D8

These two are not beta1 blockers.  We can get these in before 1.0.0:
- [x] Create "Import Config" deploy hook.  http://drushcommands.com/drush-8x/config/config-import/
- [x] Create "Export Config" hosting task.  http://drushcommands.com/drush-8x/config/config-export/  Looks like this command has `--commit`, `--message`, `--push`, `--remote`, `--branch` options already built in!
- [ ] devshop_github module can no longer detect if our SSH key is associated with the chosen account.  I spent hours trying to fix this! It used to work in devshop 0.x/Drupal6:  https://github.com/opendevshop/devmaster/blob/1.x/modules/devshop/devshop_github/devshop_github.module#L798
- [ ] Remove "Deploy from drush aliases" from main modules. create experimental module.
- [ ] Move "Acquia hooks" form element to devshop acquia module, it shouldn't appear unless that module is on.
- [ ] Add and configure admin role.
### PROJECT CREATE WIZARD
- [ ] Javascript on create wizard needs updating
- [ ] If it fails, it doesn't tell the user why anymore.
# COMPLETED
- [x] Create new branches for `1.x`.
- [x] Rebuild makefiles to use drupal 7 and new module versions.
- [x] Removing obsolete drush packages.
- [x] Create new devmaster.info install profile and update hook_install.  (Keeping devshop modules uninstalled for now.)
- [x] Debug it until it installs.
- [x] Upgrade all the devshop modules to drupal 7 with coder_upgrade.
- [x] Upgrade the boots theme to Drupal 7 (and then maybe convert it into a sub-theme of bootstrap.theme). **UPDATE:** Boots works with bootstrap theme.  Some rough edges still exist due to the upgrade. I will list as many as I can below.
- [x] Refactor devshop_provision into devmaster drush files.  Aegir 3 allows us to include all drush commands in devmaster.
- [x] Get tests going and write more tests to ensure everything works.  **UPDATE:** We need more but first step for me is getting all the pieces working.
- [x] @jonpugh | Major hook node load refactoring
- [x] @arosboro | https://github.com/opendevshop/devmaster/pull/7 | Getting devshop_github to work.
- [x] Missing project settings form on step 2 of "New Project Wizard".  See http://devshop.site/projects/add/settings
- [x] Missing Project Settings link.
  
  ![screenshot from 2016-01-26 19 46 33](https://cloud.githubusercontent.com/assets/106420/12600176/8adb0f4c-c465-11e5-9162-a0fcba65acfb.png)
- [x] @jonpugh | Funky task issues.
- [x] @llwp | https://github.com/opendevshop/devmaster/pull/16 |Custom global tasks dropdown is missing.
- [x] Sync Data task arguments for "destination" is empty.
- [x] Drush aliases for sites are getting saved as "server" type, blocking environment creation.  
- [x] "Last Task" property on environments is not saving.
- [x] Cannot deploy through web UI: "The requested page "/hosting_confirm/307/site_devshop-deploy?git_ref=development" could not be found."
- [x] Project Navigation block not loading project properly on task confirmation pages like  hosting_confirm/307/site_sync
- [x] hosting_logs aegir logs path changed in 7.x: we should set variable `provision_logs_file_path` to `/var/aegir/logs`
- [x] Run "Cache rebuild" for drupal 8 sites.
- [x] Project dashboard has a bad grid.
- [x] Platforms, Sites, and Clients should be removed from primary links.
- [x] Step 2: settings has two menu form elements.
- [x] Step 2: settings is not saving data.
- [x] Probably related - Clone Environment results in
  1. files created 
  2. an environment is created, non operational
  3. Codebase preparation failed
  4. upside: node logs are there.
  5. downside: git logs are not and enable in list of modules doesnt work yet. (/node/430)  
- [x] "Run DB Updates" and "Clear caches" should be enabled by default.
- [x] Refresh branches when there were no branches in the repository links to 404 (http://devshop.docker:8000/node//project_verify?token=26E...) 
- [x] "Environment name" textfields, like on Create Project: Step 3 and the "Create Environment" form are full width. Need to be made inline.
- [x] Collapsed fieldsets are displaying improperly.  See http://devshop.site/projects/add/git_url
- [x] Sync tasks are not showing up in environment node page task lists.
- [x] Hosting task confirm form submit no longer redirect back to the dashboard.
- [x] Site node page does not display the last task! Makes it look like it never happened.
- [x] Backups are not initiated, tasks fail. https://www.drupal.org/node/2619074  
- [x] The redirect for a project that is still being created doesn't work. Start creating a project then visit it's node page to see.

**Comment by llwp** [comment]
This is an iterative, non-trivial task: "Debug it until it installs." as is the subsequent step.

Thinking about setting up a c9 instance to collaborate on this process.  (username "mraj")
If it saves time / helps at all.

Any interest?

**Comment by jonpugh** [comment]
Just checked that box.

I'm trying to get coder upgrade running on the modules right now...

Unknown what needs to be done until that is done.

**Comment by jonpugh** [comment]
I've reviewed and applied a coder upgrade module run on all the modules in the 1.x branch.

I'm still testing install and usage.

The theme and moving provision are the next big tasks.

**Comment by jonpugh** [comment]
I have to post updated status... but I have to walk a dog.  Be back soon to be a better PM.

**Comment by Hesoyam** [comment]
"vagrant destroy" throws "Message: uninitialized constant YAML"

Fix: move "require 'yaml'" to TOF

**Comment by arosboro** [comment]
Commit 96610592185c140cc51c26d1f9aa9a9859f15119 brings the 1.x travis tests one step closer.  It sets the environment variable path before executing the command.  We may need to look at this for other devshop commands, but it could be specific to the travis docker environment.

**Comment by jonpugh** [comment]
@Hesoyam just curious, what version of vagrant are you running?  I never received that message before...  but I'm running 1.7.2

**Comment by Hesoyam** [comment]
Vagrant 1.6.5
Ubuntu repo says it's already the newest version

**Comment by jonpugh** [comment]
Ah thanks. Hope you don't mind, I updated your PR to mention the version: #51

**Comment by Hesoyam** [comment]
http://devshop.site/admin/reports/devshop_sites
```
[Thu Jan 28 08:49:41.465064 2016] [:error] [pid 8374] [client 10.10.10.1:35903] PHP Fatal error:  Call to undefined function db_fetch_object() in /var/aegir/devmaster-1.x/profiles/devmaster/modules/devshop/devshop_hosting.module on line 230
```

**Comment by arosboro** [comment]
```PHP Fatal error:  Call to undefined function devshop_projects_save_environments() in /var/aegir/devmaster-1.x/includes/form.inc on line 1519, referer: http://devshop.site/projects/add/environments```

**Comment by arosboro** [comment]
Devmaster tests in opendevshop/devmaster#7 are pulling in the 1.x branch and running drush devmaster:test correctly for ubuntu 14.04 only

**Comment by arosboro** [comment]
Looks like this doesn't take into account the pr code though

**Comment by jonpugh** [comment]
I've gone ahead and updated the default branch for devshop to 1.x.

There's still a few rough edges but if an upgrade works, I think we are close to ready for beta release.

**Comment by jonpugh** [comment]
Woof! This has been done for SO LONG.
