### ISSUE TITLE
Improve GitHub API integrations by moving Deployment and Commit status to nodes

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#381]
Right now all logic for creating commit status and deployments is in the webhook code. 

Now that we have a PR queue, we need to fire those deployment statuses and commit statuses from there, not just the webhook function.

We can map node creations and updates to deployment and commit statuses.

## Deployments
Here's the triggers needed:

- [ ] Site Node Create:
  - [ ] Deployment `queued`.
- [ ] Platform Verify or Deploy Code task Start:  
  - [ ] Deployment `pending`.
- [ ] Right before actual "Git clone" or "git pull" starts: `in_progress`.
- [ ] Platform Verify or Deploy Code task Fail during git pull or composer install:
  - [ ] Deployment `error`
- [ ] DevShop Deploy Hooks failure:
  - [ ] Deployment `failure`.
- [ ] DevShop Deploy Code task success:
  - [ ] Deployment `failure`

#### Deployment API Info

https://developer.github.com/v3/repos/deployments/

###### States
error , failure , pending , in_progress , queued , or success

## Commit "Statuses"

DevShop uses "Commit Status" to tell the user the state of the "deployment" and the "test" tasks.

This is kind of duplicating the effort of the deployment status API integration, but is a good thing because the "deployment" IS a test, should be treated as one.

Let's keep the `devshop/$PROJECT/deploy` and `devshop/$PROJECT/test` commit statuses to map to the "Deploy Code/Platform Verify" and "Run Tests" tasks. IT works now, but only in the webhooks and in drush hooks.
 
- [ ] Task Node (type: install) Create:
  - [ ] Commit Status `deploy:pending`.
  - [ ] Commit Status `test:pending` if configured to run tests.
- [ ] Platform Verify or Deploy Code task Fail during git pull or composer install:
  - [ ] Commit Status `deploy:error`. 
  - [ ] Commit Status `test:error` if configured to run tests.
- [ ] DevShop Deploy Code task failure:
  - [ ] Commit Status `deploy:failure`
- [ ] DevShop Deploy Code task success:
  - [ ] Commit Status `deploy:success`
- [ ] Run Tests task failure:
  - [ ] Commit Status `test:failure`
- [ ] Run Tests task success:
  - [ ] Commit Status `test:success`
  
##### States
 error, failure, pending, or success

**Comment by jonpugh** [comment]
I completed a bunch of these in https://github.com/opendevshop/devshop/pull/384

Let's use this to track what else needs to be done, and to figure out why deployments and commit notifications are not coming through.

**Comment by jonpugh** [comment]
Nah. the new GitHubAPI CLI deployment tools are good for this. We can integrate with those directly and avoid storing any data at all.
