### ISSUE TITLE
EPIC: DevShop Cloud

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#45]
As a devshop user
I want devshop to create more servers for me
so I don't have to.

DevShop Cloud is a collection of tools for Aegir that will allow fully automatic provisioning of cloud servers from any provider, starting with Softlayer, digitalocean, and amazon web services.

The work has been ongoing for some time in the `devshop_cloud` module in the `devshop_cloud` branch: https://github.com/opendevshop/devmaster/tree/devshop-cloud/modules/devshop/devshop_cloud

Sadly because of the separation of provision/hosting in aegir 2 and earlier, there is a separate repo you need, with the unfortunately confusing name of "devshop_cloud": https://github.com/opendevshop/devshop_cloud

My original prototye used softlayer.  @arosboro created a plugin for digital ocean. Basically, anyone with a PHP library will be really easy to add to devshop cloud.
# Steps
- [x] #30 - Finish upgrade to aegir 3.  It's not worth working on until the upgrade is complete.
- [ ] Pull https://github.com/opendevshop/devshop_cloud work into `devshop_cloud` branch of https://github.com/opendevshop/devmaster
- [ ] Create a decent "cloud server options" system. We are duplicating effort between the SL and DO plugins.
- [ ] Create a good "Server Variables" system that allows easy adding to the server's variables.
- [ ] Create an open source version of the Ansible Dynamic Inventory code we wrote for http://devshop.build

**Comment by jonpugh** [comment]
Closing. 

This cloud stuff should just move to Aegir. Including it in devshop is too much.

In the end we'd probably should completely offload cloud server creation to something like kubernetes or rancher or docker-machine, anyway.
