### ISSUE TITLE
Improve Testing User Experience

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#46]
The dream is to make getting a project ready for testing as easy as possible:
1. [x] "Prepare testing for this project" task: We can easily create a task that sets up the composer.json, composer.lock, and behat.yml scaffolding for the user, Including a simple Feature file that checks the homepage.
2. [x] Design a new system for handling multiple types of tests. We want to be able to run behat, code syntax checks, phpCS, etc.
   - [x] Notify the user if a `.hooks` or `.hooks.yml` file was found. If not, offer to create one.
   - [x] For each .hooks.yml test, ping back github a different status.
   - [x] Create a UI to show test status better.

**Comment by jonpugh** [comment]
We still need to make these improvements.

**Comment by jonpugh** [comment]
Since this issue was made, we've created the [DevShop Composer Template(https://github.com/opendevshop/devshop-behat-extension) project which includes the behat testing folder.

We also created the [provision-ops/yaml-tests](https://github.com/opendevshop/devshop-composer-template) plugin to do exactly this!

>  For each .hooks.yml test, ping back github a different status.

**Comment by jonpugh** [comment]
Any additional improvements should get new issues.
