### ISSUE TITLE
EPIC | GitHub API Improvements

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#462]
This issue will track work being done in multiple PRs.

- [x] Use default branch from repo on environment create form.
- [X] Use default branch from repo on environment create form.
- [X] Use full "install method" form on the project setting page for github "Pull request install method."
- [x] Make sure it saves and loads the data into the form correctly.
- [x] Use the project github install method settings as the default for the site.

1. [x] Switch the logic in "devshop_github_client()" to use a "must authenticate" parameter. This way we know the caller requires a token when we throw an exception for an empty one.
3. [x] Deploy tasks fail if a site was not installed because of the "validate" hook: "provision-devshop-deploy must be run on a site context". Not true: Git code deploys should always be possible.
4. [x] Git Reference type detection is broken: See Drush_devshop_provision_provision_devshop_deploy
5. [x] Check the Git Remote AND the SHA before triggering a deploy task.

## Problems for isolated servers
1. [x] Project verify tasks do not run regularly, so do not get branches updated. 
  - [x] Add a Project info update queue that updates all of a project's branches and tags every minute.
  - [x] Or, build a queue into hosting_git that updates available branches for all remotes regularly, then let the project source that data.
2. [x] GitHub PR Queue cannot handle more than one project with the same git remote. It stops at the first environment found.
3. [x] Queue should ignore projects that do not have the "Enable PR environments" checked.
4. [x] Create Deploy Queue separate from GitHub PR queue code. 
  - [x] Move logic for checking local vs remote branches and triggering tasks to Hosting_Git. 
  - [x] Give Hosting_git hooks to allow other modules to react to detected differences between local and remote: Hosting Git Pull Task Alter, hook Hosting git code Update.
5. [x] “Deploy code” task does not update stored “git ref” in hosting site platforms table.
6. [x] Bugs encountered on UL server:
  - [x] Duplicate entries/attempts to insert for PR environments.
  - [x] Creating new project from “existing github repository” throws “illegal choice detected”. The textfield for available projects isn't being parsed correctly.
7. Pull Request Sites:
  - [x] Step 3:  "Pull Request environments are disabled for this project." but they still appear. If you switch PR mode to "only create envs on create" **before** unchecking "Enable Pull Request Environments" it works correctly.
  - [x] PR Queue update still failing when an installation fails or a site delete is triggered but not complete.
  - [x] Add a unique key to the devshop environment table #437

**Comment by jonpugh** [comment]
Closed!
