### ISSUE TITLE
Create new GitHub Deployment API experience.

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#527]
# Solution:
DevShop GitHub API CLI.

# TODO:
Integrate github API CLI with new devshop install/deploy tasks.

# Requirements
- [x] Fix Existing Github Deployment notification bugs.
- [x] Pass all URLs associated with an environment to deployment notification. 
- [x] GitHub PR Environments schedule a new "install" task. Run `provision-install --force` instead.
- [x] Allow github comments to be posted where "deployment status" updates are sent. (This used to be how devshop github integration worked. Code is still there, commented out.)
  - [x] Plan for too many comments: Disable or hide previous deployment comments.
  - [x] Create a template file so users can override comment body in theme. 
  - [ ] In default comment template, link to site, site dashboard, project dashboard, and task status .
  - [ ] Add a github comment alter hook and API hook_function documentation that uses the "add additional links to github" use case. (VA.gov WEB URLs).

**Comment by jonpugh** [comment]
So we now have a composer plugin that provides a CLI for creating deployment objects, but users have to use CLI commands in scripts to implement.

With the Tasks modernization that was done in #591 , all changes come through in a single install or deploy task, so we can now more reliably implement GitHub Deployments API integration.
