### ISSUE TITLE
EPIC | Useful GitHub Comments?

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#540]
We used to post comments to github before the Deployments API worked.

There's more potential for things like reporting specific links, or specific parts of logs, etc.

Long term, let's research this. 

- [ ] Allow github comments to be posted where "deployment status" updates are sent. (This used to be how devshop github integration worked. Code is still there, commented out.)
  - [ ] Plan for too many comments: Disable or hide previous deployment comments.
  - [ ] Create a template file so users can override comment body in theme. 
  - [ ] In default comment template, link to site, site dashboard, project dashboard, and task status .
  - [ ] Add a github comment alter hook and API hook_function documentation that uses the "add additional links to github" use case.
