### ISSUE TITLE
EPIC | DevShop Tasks Improvements

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#548]
DevShop (Aegir) Tasks are quite messy. It was one of the first improvements I made to Aegir: get the javascript to be more reponsive. 

This Epic tracks all github and drupal issues related to the Hosting Tasks module.

# Issues
- [x] Block running more than X tasks at a time.
- [ ] #389 - Add Hosting Task Scheduler 
- [x] #235 - Improve "Re-install" site UX and "Protect Site" feature 
- [x] #522 - Failing platform or delete tasks wreaks havok on CI system because hosting_context record is still present.
- [x] #535 - Remove extraneous tasks when creating environments
- [x] #293 - Platform verify task should be triggered after test task.
- [x] unique environment key. (Duplicate context problem.)
- [x] #388 - GitHub Queue should check for existing running tasks.
- [x] #526 - Component: Remote Reset + Aegir Hosting Git Queue Upgrade
- [x] #534 - Fix Aegir Hosting Tasks: Queue is not working as expected.
- [x] #493 - Tasks from deleted environments appear sometimes 
- [x] #385 - Move back to using only devshop-deploy task, not platform verify.
