### ISSUE TITLE
Component / YamlTasks+GitHubApiCli / Leverage Composer's config system for GitHub Token Handing

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#576]
Composer has it's own GitHub API implementation and Token handing.

Our tools should leverage this!

This blog post explained how composer uses config to track tokens for it's own usage: https://www.previousnext.com.au/blog/managing-composer-github-access-personal-access-tokens

# Manual usage

```
# Set the token.
composer config -g github-oauth.github.com 00000TOKEN0000
# Get the token.
composer config github-oauth.github.com
```

# Tasks

- [ ] Alter GITHUB_TOKEN lookup to include composer config: github-oauth.github.com
- [ ] Implement composer's interactive GITHUB_TOKEN creator. Not sure where or how it does this yet.
- [ ] Do this in a simple global way. Many packages rely on github API usage.
