### ISSUE TITLE
Epic / Documentation

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#583]
# Tasks

- [x] #584 Add https://github.com/opendevshop/documentation as a sub repo.
  - [x] Ensure docs.opendevshop.com is still working.
  - [x] Choose new domain for docs: ~devshop.help~ or devshop.guide.
  - [x] Set up new domain with gitbook! docs.devshop.guide.
- [ ] Merge in outstanding pulls from documentation repo: https://github.com/opendevshop/documentation/pulls

#### Guides

- [ ] Docker
- [ ] VirtualBox/VMWare
- [ ] AWS
- [ ] DigitalOcean
- [ ] Linode

#### Release Process
- [ ] Requirements for RC
- [ ]

**Comment by scottwolpow** [comment]
I will work on AWS and Linode

**Comment by jonpugh** [comment]
Nice! Now users can fork the main repo to update docs as well as source code.

New documentation domain is https://devshop.guide! 💁
