### ISSUE TITLE
DevShop CLI Improvements

### ISSUE THREAD

**Issue by jonpugh** [opendevshop/devshop#6]
~~Currently managing devshop on a holistic level is hard.  Let's create a "DevShop CLI" for managing things like installation, upgrades, and remote install.~~

**UPDATE:** The DevShop CLI makes upgrading a devshop server really, really easy. Let's keep developing this tool to make everything else easy.
- [x] DevShop Installer: This works by guiding the user through getting the latest install script and running it.  Not sure how useful this is because you have to install the devshop CLI before installing devshop itself, so it's actually an extra step compared to the standalone SH script installer.
- [x] Remote Server Install: Works!  
- [x] DevShop Upgrade.  ~~Still has bugs!  Need to fix these before the next release.~~ **UPDATE:** We've been running devshop upgrades for our entire platform for every release since Dec 2015.
  - [x] Remote Server Create: We should do the heavy lifting for DevShop Cloud with a `server:create` command.
- [ ] Separate this tool from the main devshop repo.  It seems to me it would be better to make the CLI a separate repo so that it can be turned into a PHAR package.
- [ ] Change the install.sh script to install devshop CLI phar dependencies only, then run `devshop install`
- [ ] Incorporate parts of http://github.com/jonpugh/director in order to start using ansible galaxy roles for everything.

**Comment by jonpugh** [comment]
In progress!

**Comment by jonpugh** [comment]
Devshop installer is done, remote installer is done, upgrader is ok but I had problems running it. Needs more testing.

**Comment by jonpugh** [comment]
`devshop upgrade` command has worked for a while now. We have been using it to upgrade our customer devshops since Dec 2015

**Comment by llwp** [comment]
so the next heavy lift looks to be separating it into a different repo... do we want to talk about drupal console?

**Comment by madalinignisca** [comment]
`drupal devshop:install`
`drupal devshop:status`
`drupal devshop:upgrade`
`drupal devshop:server:create`

etc...

This would be nice, but I doubt that most would be pleased to just increase the drupal console a lot.

Devshop should be decoupled and independent, should be able to wrap around drupal console for certain small needs, like starting a new Drupal website instead of deploying from git etc.

**Comment by jonpugh** [comment]
The current CLI functionality does need to be cleaned up and more clearly defined and documented.

Adding NeedsTriage label so we can review later.
